#sample:
#    name: Sample
#    file: path/to/sample.md
#    position:
#        x: 34
#        y: 9 * sin(23)
#        z: 0
#    rotation:
#        x: 3.14159265358979323846264338327950288419716939937510494459582097
#        y: 0.1
#        z: 2


#Accueil

accueil:
    name: Accueil
    file: accueil.html
    isHead: true
    color: "#000"

cartographie:
    name: Cartographie de la controverse
    file: accueil/cartographie.html

chronologie-controverse:
    name: Chronologie de la controverse
    file: accueil/chronologie-controverse.html
    color: "e74c3c"

acteurs:
    name: Acteurs de la controverse
    file: accueil/acteurs.html

equipe:
    name: Qui sommes-nous ?
    file: accueil/equipe.html

clause-non-responsabilite:
    name: Clause de non-responsabilité
    file: accueil/responsabilite.html

bibliographie:
    name: Bibliographie
    file: accueil/bibliographie.md

# Chronologie


chronologie-globale:
    name: Chronologie de l'étude de cas
    file: chronologie/0-global.html
    isHead: true
    color: "#e74c3c"

chronologie-1:
    name: Prélude
    file: chronologie/1-frise.html
    color: "#F9B256"

chronologie-2:
    name: Fermeture des voies sur berges (rive gauche)
    file: chronologie/2-frise.html
    color: "#AFD39A"

chronologie-3:
    name: Annonces pour la rive droite
    file: chronologie/3-frise.html
    color: "#AEC6FF"

chronologie-4:
    name: Étude d’impact et débats
    file: chronologie/4-frise.html
    color: "#F29FC5"

chronologie-5:
    name: Fermeture des voies sur berges (rive droite)
    file: chronologie/5-frise.html
    color: "#E30613"

chronologie-6:
    name: Étude de suivi par le comité régional
    file: chronologie/6-frise.html
    color: "#8BADDC"

chronologie-7:
    name: Justice : réouverture aux voitures rive droite
    file: chronologie/7-frise.html
    color: "#f7d762"

chronologie-8:
    name: Fermeture avec de nouveaux arguments
    file: chronologie/8-frise.html
    color: "#7FD8CA"

# Etude de cas

etude-de-cas:
    name: Étude de cas
    file: etude-de-cas/presentation.html
    isHead: true
    color: "#f1c40f"
    illustration: etude-de-cas/quaisBas.png

bazar-et-etude-de-cas:
    name: Les prévisions de la mairie sont-elles réalistes ?
    file: etude-de-cas/1-bazar-et-etude-de-cas.md

combat-du-siecle-des-comites:
    name: Comment mesurer les conséquences ?
    file: etude-de-cas/2-combat-du-siecle-des-comites.md

impact-sur-la-circulation:
    name: Comment mesurer l’impact sur la circulation ?
    file: etude-de-cas/3-impact-sur-la-circulation.md

impact-sur-la-pollution:
    name: La qualité de l'air s'est-elle améliorée ?
    file: etude-de-cas/4-impact-sur-la-pollution.md

economie-locale:
    name: Au-delà de la pollution, un impact économique et social ?
    file: etude-de-cas/5-economie-locale.md

# approche thématique

approche-thematique:
    name: Approche thématique
    file: approche-thematique/approche_thematique.html
    isHead: true
    color: "#2ecc71"
    new_page: true

# qui s'occupe du problème ?

qui-est-concerne:
    name: Qui est concerné ?
    type: title-2
    file: approche-thematique/qui-s-occupe-du-probleme-qui-est-concerne-par-la-question/qui-est-concerne.md
    illustration: approche-thematique/illustrations/qui_est_concerne.jpg
    new_page: true

competence-territoriale:
    name: Compétences territoriale
    file: approche-thematique/qui-s-occupe-du-probleme-qui-est-concerne-par-la-question/competences-territoriales/competence-territoriale.md
    illustration: approche-thematique/illustrations/champsHiver.png

qui-est-consulte:
    name: Qui est consulté ?
    file: approche-thematique/qui-s-occupe-du-probleme-qui-est-concerne-par-la-question/qui-est-consulte/qui-est-consulte.md
    illustration: approche-thematique/illustrations/qui_est_consulte.jpg

# comment gouverner

modeles-encadrement:
    name: Quels sont les modèles d'encadrement d'une ville ?
    type: title-2
    file: ~
    illustration: approche-thematique/illustrations/modeles_encadrement.jpg
    new_page: true

court-terme:
    name: Mise en place de politiques à court terme
    type: title-3
    illustration: approche-thematique/illustrations/RG.png
    file: ~

mesures-contraindre-vehicules:
    name: Des mesures pour contraindre les véhicules
    file: approche-thematique/comment-gouverner-une-ville-quels-sont-les-modeles-d-encadrement-d-une-ville/a-court-terme/mise-en-place-de-mesure-pour-contraindre-les-vehicules.md
    illustration: approche-thematique/illustrations/RGpont.png

selectionner-vehicules:
    name: Sélectionner les véhicules
    file: approche-thematique/comment-gouverner-une-ville-quels-sont-les-modeles-d-encadrement-d-une-ville/a-court-terme/selectionner-vehicules.md
    illustration: approche-thematique/illustrations/rivoli.png

mobilites-alternatives:
    name: Favoriser les mobilités alternatives
    file: approche-thematique/comment-gouverner-une-ville-quels-sont-les-modeles-d-encadrement-d-une-ville/a-court-terme/mobilites-alternatives.md
    illustration: approche-thematique/comment-gouverner-une-ville-quels-sont-les-modeles-d-encadrement-d-une-ville/a-court-terme/velo.png

long-terme:
    name: Vision sur le long terme : suivre le progrès technique
    type: title-3
    file: ~
    illustration: approche-thematique/illustrations/vision_long_terme.jpg

vehicules-thermiques:
    name: Renouvellement du parc automobile : des véhicules thermiques plus propres ?
    file: approche-thematique/comment-gouverner-une-ville-quels-sont-les-modeles-d-encadrement-d-une-ville/a-long-terme/suivre-le-progres-technique/1-vehicules-thermiques.md

voiture-electrique:
    name: La voiture électrique : alternative future à la voiture thermique ?
    file: approche-thematique/comment-gouverner-une-ville-quels-sont-les-modeles-d-encadrement-d-une-ville/a-long-terme/suivre-le-progres-technique/2-voiture-electrique.md

vehicules-autonomes:
    name: Les véhicules autonomes bientôt sur les routes ?
    file: approche-thematique/comment-gouverner-une-ville-quels-sont-les-modeles-d-encadrement-d-une-ville/a-long-terme/suivre-le-progres-technique/3-vehicules-autonomes.md
    menu_sep: true

#quantifier

probleme-mesure:
    name: Le problème de la mesure
    type: title-2
    file: ~
    illustration: approche-thematique/illustrations/mesures.png
    new_page: true

comment-prevoir-les-consequences:
    name: Que faut-il mesurer ?
    file: approche-thematique/comment-mesurer-quantifier/1-comment-prevoir-les-consequences.md

mais-comment-verifier-la-concordance-entre-previsions-et-realite:
    name: Qui réalise les mesures ?
    file: approche-thematique/comment-mesurer-quantifier/2-mais-comment-verifier-la-concordance-entre-previsions-et-realite.md

airparif:
    name: Divergence des interprétations
    file: approche-thematique/comment-mesurer-quantifier/3-airparif.md
    menu_sep: true

#quelles-sont-les-inegalites-engendrees

inegalites-engendrees:
    name: Quelles sont les inégalités engendrées ?
    type: title-2
    file: ~
    illustration: approche-thematique/illustrations/inegalites_spatiales.jpg
    new_page: true

inegalites-spatiales:
    name: Inégalités spatiales : les banlieues trop souvent laissées à l’écart
    file: approche-thematique/quelles-sont-les-inegalites-engendrees/inegalites-spatiales.md

inegalites-socioprofessionnelle:
    name: Impact sur l'économie locale
    file: approche-thematique/quelles-sont-les-inegalites-engendrees/socioprofessionelles.md
    illustration: approche-thematique/illustrations/inegalites_pros.jpg

classes-modestes:
    name: Les classes modestes les plus impactées ?
    file: approche-thematique/quelles-sont-les-inegalites-engendrees/classes-modestes.md
