#sample:
#    name: Sample
#    file: path/to/sample.md
#    position:
#        x: 34
#        y: 9 * sin(23)
#        z: 0
#    rotation:
#        x: 3.1415925
#        y: 0.1
#        z: 2


#Accueil

accueil:
    name: Accueil
    file: accueil.html
    isHead: true
    color: "#000"

cartographie:
    name: Cartographie de la controverse
    file: accueil/cartographie.html

equipe:
    name: Qui sommes nous ?
    file: accueil/equipe.html

clause-non-responsabilite:
    name: Clause de non responsabilité
    file: accueil/responsabilite.html

bibliographie:
    name: Bibliographie
    file: accueil/bibliographie.md

# Chronologie


chronologie-globale:
    name: Chronologie
    file: chronologie/0-global.html
    isHead: true
    color: "#e74c3c"

chronologie-1:
    name: Prélude
    file: chronologie/1-frise.html

chronologie-2:
    name: Fermeture des voies sur berge (rive gauche)
    file: chronologie/2-frise.html

chronologie-3:
    name: Annonces pour la rive droite
    file: chronologie/3-frise.html

chronologie-4:
    name: Etude d'impact et débats
    file: chronologie/4-frise.html

chronologie-5:
    name: Fermeture des voies sur berge (rive droite)
    file: chronologie/5-frise.html

chronologie-6:
    name: Étude de suivi par le comité Régional
    file: chronologie/6-frise.html

chronologie-7:
    name: "Justice : réouverture aux voitures rive droite"
    file: chronologie/7-frise.html

chronologie-8:
    name: Fermeture avec de nouveaux arguments
    file: chronologie/8-frise.html



# Etude de cas

etude-de-cas:
    name: Etude de cas
    file: etude-de-cas/presentation.html
    isHead: true
    color: "#f1c40f"

bazar-et-etude-de-cas:
    name: Bazar et étude de cas
    file: etude-de-cas/1-bazar-et-etude-de-cas.md

combat-du-siecle-des-comites:
    name: Combat du siècle des comités
    file: etude-de-cas/2-combat-du-siecle-des-comites.md

impact-sur-la-circulation:
    name: Impact sur la circulation
    file: etude-de-cas/3-impact-sur-la-circulation.md

encadre-qui-sont-les-victimes-de-la-pollution:
    name: Qui sont les victimes de la pollution
    file: etude-de-cas/4-encadre-qui-sont-les-victimes-de-la-pollution.md

impact-sur-la-pollution:
    name: Impact sur la pollution
    file: etude-de-cas/4-impact-sur-la-pollution.md

economie-locale:
    name: L'économie locale
    file: etude-de-cas/5-economie-locale.md

des-inegalites-renforcees:
    name: Des inégalités renforcées ?
    file: etude-de-cas/6-des-inegalites-renforcees.md

# approche thématique

approche-thematique:
    name: Approche thématique
    file: approche-thematique/approche_thematique.html
    isHead: true
    color: "#2ecc71"

# qui s'occupe du problème ?

qui-est-concerne:
    name: Qui est concerné ?
    type: title-2
    file: ~

competence-territoriale:
    name: Compétences territoriale
    file: approche-thematique/qui-s-occupe-du-probleme-qui-est-concerne-par-la-question/competences-territoriales/competence-territoriale.md

qui-est-consulte:
    name: Qui est consulté ?
    file: approche-thematique/qui-s-occupe-du-probleme-qui-est-concerne-par-la-question/qui-est-consulte/qui-est-consulte.md

# comment gouverner

modeles-encadrement:
    name: Quels sont les modeles d'encadrement d'une ville ?
    type: title-2
    file: ~

court-terme:
    name: Mise en place de politiques à court terme
    type: title-3
    file: ~

mesures-contraindre-vehicules:
    name: Les mesures pour contraindre les véhicules
    file: approche-thematique/comment-gouverner-une-ville-quels-sont-les-modeles-d-encadrement-d-une-ville/a-court-terme/mise-en-place-de-mesure-pour-contraindre-les-vehicules.md

selectionner-vehicules:
    name: Séléctionner les véhicules ?
    file: approche-thematique/comment-gouverner-une-ville-quels-sont-les-modeles-d-encadrement-d-une-ville/a-court-terme/selectionner-vehicules.md

mobilites-alternatives:
    name: Les mobilités alternatives
    file: approche-thematique/comment-gouverner-une-ville-quels-sont-les-modeles-d-encadrement-d-une-ville/a-court-terme/mobilites-alternatives.md


long-terme:
    name: "Vision sur le long terme : le progrès technique"
    type: title-3
    file: ~

vehicules-thermiques:
    name: Des véhicules thermiques plus propres ?
    file: approche-thematique/comment-gouverner-une-ville-quels-sont-les-modeles-d-encadrement-d-une-ville/a-long-terme/suivre-le-progres-technique/1-vehicules-thermiques.md

voiture-electrique:
    name: "La voiture électrique : alternative future à la voiture thermique ?"
    file: approche-thematique/comment-gouverner-une-ville-quels-sont-les-modeles-d-encadrement-d-une-ville/a-long-terme/suivre-le-progres-technique/2-voiture-electrique.md

vehicules-autonomes:
    name: Les véhicules autonomes bientôt sur les routes ?
    file: approche-thematique/comment-gouverner-une-ville-quels-sont-les-modeles-d-encadrement-d-une-ville/a-long-terme/suivre-le-progres-technique/3-vehicules-autonomes.md
    menu_sep: true

#quantifier

comment-prevoir-les-consequences:
    name: Impact sur la pollution ?
    file: approche-thematique/comment-mesurer-quantifier/1-comment-prevoir-les-consequences.md

mais-comment-verifier-la-concordance-entre-previsions-et-realite:
    name: Impact sur le trafic ?
    file: approche-thematique/comment-mesurer-quantifier/2-mais-comment-verifier-la-concordance-entre-previsions-et-realite.md

airparif:
    name: Divergence des interprétations
    file: approche-thematique/comment-mesurer-quantifier/3-airparif.md
    menu_sep: true

#quelles-sont-les-inegalites-engendrees

inegalites-engendrees:
    name: Quelles sont les inégalités engendrées ?
    type: title-2
    file: ~

inegalites-spatiales:
    name: Les inégalités spatiales
    file: approche-thematique/quelles-sont-les-inegalites-engendrees/inegalites-spatiales.md

inegalites-socioprofessionnelle:
    name: Inégalités socioprofessionnels
    file: approche-thematique/quelles-sont-les-inegalites-engendrees/socioprofessionelles.md
